"""

Revision ID: 12cccac924f4
Revises: 132523f1bc82
Create Date: 2026-05-18 15:18:43.616887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12cccac924f4'
down_revision: Union[str, None] = '132523f1bc82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gold_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_produtos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gold_categoria', schema=None) as batch_op:
        batch_op.drop_column('total_produtos')

    # ### end Alembic commands ###
