"""adiciona_telefone_email_em_clientes

Revision ID: 132523f1bc82
Revises: 4851deabeb80
Create Date: 2026-05-18 13:50:03.238635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132523f1bc82'
down_revision: Union[str, None] = '4851deabeb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('telefone', sa.String(), nullable=True))

    with op.batch_alter_table('fato_suporte_ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registro_consistente', sa.Boolean(), nullable=True))

    with op.batch_alter_table('gold_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_estoque_disponivel', sa.Integer(), nullable=True))
        batch_op.drop_column('total_produtos')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gold_categoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_produtos', sa.INTEGER(), nullable=True))
        batch_op.drop_column('total_estoque_disponivel')

    with op.batch_alter_table('fato_suporte_ticket', schema=None) as batch_op:
        batch_op.drop_column('registro_consistente')

    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.drop_column('telefone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
