"""empty message

Revision ID: 4851deabeb80
Revises: 
Create Date: 2026-05-18 11:27:18.224500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4851deabeb80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_cliente',
    sa.Column('id_cliente', sa.String(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.Column('qtd_pedidos_realizados', sa.Integer(), nullable=True),
    sa.Column('total_gasto_brl', sa.Float(), nullable=True),
    sa.Column('qtd_tickets_suporte', sa.Integer(), nullable=True),
    sa.Column('data_ultima_compra', sa.DateTime(), nullable=True),
    sa.Column('media_estrelas_dadas', sa.Float(), nullable=True),
    sa.Column('segmento_rfm', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dim_cliente_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_cliente_segmento_rfm'), ['segmento_rfm'], unique=False)

    op.create_table('gold_categoria',
    sa.Column('id_categoria', sa.String(), nullable=False),
    sa.Column('nome_categoria', sa.String(), nullable=False),
    sa.Column('imagem_url', sa.String(), nullable=True),
    sa.Column('total_produtos', sa.Integer(), nullable=True),
    sa.Column('total_produtos_ativos', sa.Integer(), nullable=True),
    sa.Column('total_com_estoque', sa.Integer(), nullable=True),
    sa.Column('preco_medio', sa.Float(), nullable=True),
    sa.Column('preco_minimo', sa.Float(), nullable=True),
    sa.Column('preco_maximo', sa.Float(), nullable=True),
    sa.Column('peso_medio_kg', sa.Float(), nullable=True),
    sa.Column('total_precisa_revisao', sa.Integer(), nullable=True),
    sa.Column('slug_categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    with op.batch_alter_table('gold_categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_categoria_id_categoria'), ['id_categoria'], unique=False)

    op.create_table('gold_operador',
    sa.Column('id_operador', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id_operador')
    )
    with op.batch_alter_table('gold_operador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gold_operador_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_gold_operador_id_operador'), ['id_operador'], unique=False)
        batch_op.create_index(batch_op.f('ix_gold_operador_username'), ['username'], unique=True)

    op.create_table('ai_agent_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('history_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['gold_operador.id_operador'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', name='uq_ai_agent_sessions_user_session')
    )
    with op.batch_alter_table('ai_agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_agent_sessions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_agent_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('dim_produto',
    sa.Column('id_produto', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('nome_produto', sa.String(), nullable=False),
    sa.Column('id_categoria', sa.String(), nullable=True),
    sa.Column('fornecedor', sa.String(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('estoque_disponivel', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.String(), nullable=True),
    sa.Column('precisa_revisao', sa.String(), nullable=True),
    sa.Column('data_cadastro_produto', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_pedidos', sa.Integer(), nullable=True),
    sa.Column('receita_total', sa.Float(), nullable=True),
    sa.Column('ticket_medio', sa.Float(), nullable=True),
    sa.Column('total_unidades_vendidas', sa.Integer(), nullable=True),
    sa.Column('total_avaliacoes', sa.Integer(), nullable=True),
    sa.Column('media_nota_produto', sa.Float(), nullable=True),
    sa.Column('media_nota_nps', sa.Float(), nullable=True),
    sa.Column('pct_recomendacoes_sim', sa.Float(), nullable=True),
    sa.Column('media_tempo_resolucao_horas', sa.Float(), nullable=True),
    sa.Column('media_nota_suporte', sa.Float(), nullable=True),
    sa.Column('total_tickets', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_categoria'], ['gold_categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_produto')
    )
    with op.batch_alter_table('dim_produto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dim_produto_id_categoria'), ['id_categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_produto_id_produto'), ['id_produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_dim_produto_sku'), ['sku'], unique=False)

    op.create_table('fato_vendas',
    sa.Column('id_pedido', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=False),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('id_pedido_display', sa.String(), nullable=False),
    sa.Column('id_data', sa.String(), nullable=True),
    sa.Column('quantidade_vendas', sa.Integer(), nullable=True),
    sa.Column('valor_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total_venda', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('metodo_pagamento', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['dim_cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['dim_produto.id_produto'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    with op.batch_alter_table('fato_vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_data'), ['id_data'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_pedido_display'), ['id_pedido_display'], unique=True)
        batch_op.create_index(batch_op.f('ix_fato_vendas_id_produto'), ['id_produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_vendas_status'), ['status'], unique=False)

    op.create_table('fato_suporte_ticket',
    sa.Column('id_ticket', sa.String(), nullable=False),
    sa.Column('id_cliente', sa.String(), nullable=False),
    sa.Column('id_pedido', sa.String(), nullable=True),
    sa.Column('id_produto', sa.String(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_resolucao', sa.DateTime(), nullable=True),
    sa.Column('tempo_resolucao_horas', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('tipo_problema', sa.String(), nullable=True),
    sa.Column('agente_suporte', sa.String(), nullable=True),
    sa.Column('nota_avaliacao', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['dim_cliente.id_cliente'], ),
    sa.ForeignKeyConstraint(['id_pedido'], ['fato_vendas.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_produto'], ['dim_produto.id_produto'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_ticket')
    )
    with op.batch_alter_table('fato_suporte_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fato_suporte_ticket_id_cliente'), ['id_cliente'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_suporte_ticket_id_pedido'), ['id_pedido'], unique=False)
        batch_op.create_index('ix_fato_suporte_ticket_id_pedido_status', ['id_pedido', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_suporte_ticket_id_produto'), ['id_produto'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_suporte_ticket_id_ticket'), ['id_ticket'], unique=False)
        batch_op.create_index(batch_op.f('ix_fato_suporte_ticket_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fato_suporte_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fato_suporte_ticket_status'))
        batch_op.drop_index(batch_op.f('ix_fato_suporte_ticket_id_ticket'))
        batch_op.drop_index(batch_op.f('ix_fato_suporte_ticket_id_produto'))
        batch_op.drop_index('ix_fato_suporte_ticket_id_pedido_status')
        batch_op.drop_index(batch_op.f('ix_fato_suporte_ticket_id_pedido'))
        batch_op.drop_index(batch_op.f('ix_fato_suporte_ticket_id_cliente'))

    op.drop_table('fato_suporte_ticket')
    with op.batch_alter_table('fato_vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fato_vendas_status'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_produto'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_pedido_display'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_pedido'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_data'))
        batch_op.drop_index(batch_op.f('ix_fato_vendas_id_cliente'))

    op.drop_table('fato_vendas')
    with op.batch_alter_table('dim_produto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_produto_sku'))
        batch_op.drop_index(batch_op.f('ix_dim_produto_id_produto'))
        batch_op.drop_index(batch_op.f('ix_dim_produto_id_categoria'))

    op.drop_table('dim_produto')
    with op.batch_alter_table('ai_agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_agent_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_ai_agent_sessions_session_id'))

    op.drop_table('ai_agent_sessions')
    with op.batch_alter_table('gold_operador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gold_operador_username'))
        batch_op.drop_index(batch_op.f('ix_gold_operador_id_operador'))
        batch_op.drop_index(batch_op.f('ix_gold_operador_email'))

    op.drop_table('gold_operador')
    with op.batch_alter_table('gold_categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gold_categoria_id_categoria'))

    op.drop_table('gold_categoria')
    with op.batch_alter_table('dim_cliente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dim_cliente_segmento_rfm'))
        batch_op.drop_index(batch_op.f('ix_dim_cliente_id_cliente'))

    op.drop_table('dim_cliente')
    # ### end Alembic commands ###
