"""add_composite_indexes_to_orders_and_clients

Revision ID: 94c520ebfa91
Revises: 132523f1bc82
Create Date: 2026-05-18 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c520ebfa91'
down_revision = '132523f1bc82'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_fato_vendas_id_cliente_id_pedido', 'fato_vendas', ['id_cliente', 'id_pedido'], unique=False)
    op.create_index('ix_fato_vendas_status_id_pedido', 'fato_vendas', ['status', 'id_pedido'], unique=False)
    op.create_index('ix_dim_cliente_segmento_id', 'dim_cliente', ['segmento_rfm', 'id_cliente'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_dim_cliente_segmento_id', table_name='dim_cliente')
    op.drop_index('ix_fato_vendas_status_id_pedido', table_name='fato_vendas')
    op.drop_index('ix_fato_vendas_id_cliente_id_pedido', table_name='fato_vendas')
    # ### end Alembic commands ###
